#
# Basic settings.
#
#baseurl: http://localhost:4000
baseurl: http://luqitao.github.io
title: luqitao's Blog.
#description: luqitao's Blog.
avatar: /assets/img/dmx.jpg
language: ja


#
# Icons
#
icons:
  rss: true
  email: luqt2011@163.com
  github: luqitao
  bitbucket:
  twitter: luqitao
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin:  # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: # e.g. UA-000000-01
disqus: prettyverbose

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons: false
ogp:
  image_url: http://luqitao.github.io/assets/img/dmx.jpg
   #image_url: /assets/img/dmx.jpg
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
gems:
   - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
